# -*- coding: utf-8 -*-
"""Android_Fraud_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6tyVDrV5fPN_hhr9o3mRallJh3--YOZ
"""

"""
================================================================================
FRAUD DETECTION ANDROID APP
Mobile Application for Real-Time Fraud Detection
================================================================================

FEATURES:
- Native Android interface
- Real-time fraud detection
- Account management
- Transaction monitoring
- Risk analytics
- Offline capability

INSTALLATION:
pip install kivy kivymd

TO BUILD APK:
pip install buildozer
buildozer init
buildozer -v android debug

TO RUN ON COMPUTER:
python fraud_detection_android.py

================================================================================
"""
from kivy.app import App
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.gridlayout import GridLayout
from kivy.uix.scrollview import ScrollView
from kivy.uix.label import Label
from kivy.uix.button import Button
from kivy.uix.textinput import TextInput
from kivy.uix.spinner import Spinner
from kivy.properties import StringProperty, NumericProperty, BooleanProperty
from kivy.clock import Clock
from kivy.graphics import Color, RoundedRectangle
from datetime import datetime, timedelta
from typing import List, Dict, Any
import json

# ============================================================================
# FRAUD DETECTION ENGINE (Same as before)
# ============================================================================

def mean(data):
    """Calculate mean of a list"""
    return sum(data) / len(data) if data else 0

class Transaction:
    def __init__(self, transaction_id: str, account_id: str, amount: float,
                 transaction_type: str, merchant: str, location: str,
                 timestamp: str = None, device_id: str = None):
        self.transaction_id = transaction_id
        self.account_id = account_id
        self.amount = amount
        self.transaction_type = transaction_type
        self.merchant = merchant
        self.location = location
        self.timestamp = timestamp or datetime.now().isoformat()
        self.device_id = device_id
        self.risk_score = 0.0
        self.fraud_probability = 0.0
        self.is_flagged = False
        self.flags = []
        self.investigation_status = "pending"

class Account:
    def __init__(self, account_id: str, customer_name: str,
                 account_type: str, balance: float):
        self.account_id = account_id
        self.customer_name = customer_name
        self.account_type = account_type
        self.balance = balance
        self.transactions: List[Transaction] = []
        self.typical_locations = set()
        self.avg_transaction_amount = 0.0
        self.is_frozen = False
        self.fraud_history = []

    def add_transaction(self, transaction: Transaction):
        self.transactions.append(transaction)
        self.typical_locations.add(transaction.location)
        self._update_statistics()

    def _update_statistics(self):
        if self.transactions:
            amounts = [t.amount for t in self.transactions if not t.is_flagged]
            if amounts:
                self.avg_transaction_amount = mean(amounts)

    def get_transaction_history(self, days: int = 30) -> List[Transaction]:
        cutoff_date = datetime.now() - timedelta(days=days)
        return [t for t in self.transactions
                if datetime.fromisoformat(t.timestamp) >= cutoff_date]

class FraudDetector:
    def __init__(self):
        self.high_amount_threshold = 5000
        self.velocity_threshold = 5
        self.location_change_time_threshold = 1
        self.unusual_amount_multiplier = 3
        self.high_risk_locations = {'Unknown', 'Foreign', 'High-Risk Country'}
        self.weights = {
            'amount_anomaly': 0.25,
            'velocity': 0.20,
            'location_anomaly': 0.20,
            'time_anomaly': 0.15,
            'merchant_risk': 0.10,
            'device_anomaly': 0.10
        }

    def detect_fraud(self, transaction: Transaction, account: Account) -> Dict[str, Any]:
        flags = []
        risk_scores = {}

        amount_risk = self._check_amount_anomaly(transaction, account)
        risk_scores['amount_anomaly'] = amount_risk
        if amount_risk > 50:
            flags.append(f"Unusual amount: ${transaction.amount:.2f}")

        velocity_risk = self._check_velocity(transaction, account)
        risk_scores['velocity'] = velocity_risk
        if velocity_risk > 50:
            flags.append("High transaction velocity")

        location_risk = self._check_location_anomaly(transaction, account)
        risk_scores['location_anomaly'] = location_risk
        if location_risk > 50:
            flags.append(f"Unusual location: {transaction.location}")

        time_risk = self._check_time_anomaly(transaction, account)
        risk_scores['time_anomaly'] = time_risk
        if time_risk > 50:
            flags.append("Unusual time")

        merchant_risk = self._check_merchant_risk(transaction)
        risk_scores['merchant_risk'] = merchant_risk
        if merchant_risk > 50:
            flags.append(f"High-risk merchant")

        device_risk = self._check_device_anomaly(transaction, account)
        risk_scores['device_anomaly'] = device_risk
        if device_risk > 50:
            flags.append("New device")

        total_risk = sum(risk_scores[key] * self.weights[key] for key in risk_scores.keys())
        fraud_probability = self._calculate_fraud_probability(risk_scores)
        is_fraudulent = total_risk >= 60 or fraud_probability >= 0.7

        transaction.risk_score = total_risk
        transaction.fraud_probability = fraud_probability
        transaction.is_flagged = is_fraudulent
        transaction.flags = flags

        return {
            'transaction_id': transaction.transaction_id,
            'is_fraudulent': is_fraudulent,
            'risk_score': round(total_risk, 2),
            'fraud_probability': round(fraud_probability, 2),
            'flags': flags,
            'recommendation': self._get_recommendation(total_risk, fraud_probability)
        }

    def _check_amount_anomaly(self, transaction: Transaction, account: Account) -> float:
        if not account.transactions or len(account.transactions) < 3:
            return 0.0
        avg_amount = account.avg_transaction_amount
        if avg_amount == 0:
            return 0.0
        ratio = transaction.amount / avg_amount
        if transaction.amount > self.high_amount_threshold:
            return 90.0
        elif ratio > self.unusual_amount_multiplier:
            return min(ratio * 20, 100)
        return 0.0

    def _check_velocity(self, transaction: Transaction, account: Account) -> float:
        recent_transactions = account.get_transaction_history(days=1)
        if len(recent_transactions) < 2:
            return 0.0
        one_hour_ago = datetime.now() - timedelta(hours=1)
        recent_hour = [t for t in recent_transactions
                      if datetime.fromisoformat(t.timestamp) >= one_hour_ago]
        count = len(recent_hour)
        return min(count * 15, 100) if count >= self.velocity_threshold else 0.0

    def _check_location_anomaly(self, transaction: Transaction, account: Account) -> float:
        if transaction.location in self.high_risk_locations:
            return 80.0
        if len(account.typical_locations) > 3:
            if transaction.location not in account.typical_locations:
                return 60.0
        return 0.0

    def _check_time_anomaly(self, transaction: Transaction, account: Account) -> float:
        trans_time = datetime.fromisoformat(transaction.timestamp)
        hour = trans_time.hour
        if 2 <= hour <= 5:
            return 50.0
        return 0.0

    def _check_merchant_risk(self, transaction: Transaction) -> float:
        high_risk_keywords = ['casino', 'gambling', 'crypto', 'offshore']
        merchant_lower = transaction.merchant.lower()
        for keyword in high_risk_keywords:
            if keyword in merchant_lower:
                return 70.0
        return 0.0

    def _check_device_anomaly(self, transaction: Transaction, account: Account) -> float:
        if not transaction.device_id:
            return 30.0
        known_devices = set(t.device_id for t in account.transactions if t.device_id)
        if len(known_devices) > 0 and transaction.device_id not in known_devices:
            return 50.0
        return 0.0

    def _calculate_fraud_probability(self, risk_scores: Dict[str, float]) -> float:
        high_risk_count = sum(1 for score in risk_scores.values() if score > 60)
        avg_risk = mean(list(risk_scores.values()))
        if high_risk_count >= 3:
            return 0.9
        elif high_risk_count >= 2:
            return 0.75
        elif avg_risk > 50:
            return 0.6
        return avg_risk / 100

    def _get_recommendation(self, risk_score: float, fraud_probability: float) -> str:
        if risk_score >= 80 or fraud_probability >= 0.85:
            return "BLOCK IMMEDIATELY"
        elif risk_score >= 60 or fraud_probability >= 0.7:
            return "REVIEW REQUIRED"
        elif risk_score >= 40 or fraud_probability >= 0.5:
            return "MONITOR"
        return "APPROVE"

class FraudDetectionSystem:
    def __init__(self):
        self.accounts: Dict[str, Account] = {}
        self.transactions: Dict[str, Transaction] = {}
        self.detector = FraudDetector()
        self.flagged_transactions = []

    def create_account(self, account: Account):
        self.accounts[account.account_id] = account

    def process_transaction(self, transaction: Transaction) -> Dict[str, Any]:
        if transaction.account_id not in self.accounts:
            return {"error": "Account not found"}

        account = self.accounts[transaction.account_id]
        if account.is_frozen:
            return {"status": "blocked", "reason": "Account frozen"}

        detection_result = self.detector.detect_fraud(transaction, account)
        self.transactions[transaction.transaction_id] = transaction
        account.add_transaction(transaction)

        if detection_result['is_fraudulent']:
            self.flagged_transactions.append(transaction)

        return {
            "status": "blocked" if detection_result['risk_score'] >= 80 else "processed",
            "transaction_id": transaction.transaction_id,
            "detection_result": detection_result
        }

    def get_statistics(self) -> Dict[str, Any]:
        total_transactions = len(self.transactions)
        flagged_count = len(self.flagged_transactions)
        fraud_rate = (flagged_count / total_transactions) * 100 if total_transactions > 0 else 0.0
        total_amount = sum(t.amount for t in self.transactions.values())
        flagged_amount = sum(t.amount for t in self.flagged_transactions)

        return {
            "total_transactions": total_transactions,
            "flagged_transactions": flagged_count,
            "fraud_detection_rate": round(fraud_rate, 2),
            "total_transaction_volume": round(total_amount, 2),
            "flagged_amount": round(flagged_amount, 2),
            "active_accounts": len(self.accounts)
        }

# ============================================================================
# KIVY UI SCREENS
# ============================================================================

class DashboardScreen(Screen):
    total_txns = StringProperty("0")
    flagged_txns = StringProperty("0")
    fraud_rate = StringProperty("0%")
    risk_amount = StringProperty("$0")

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.name = 'dashboard'

    def on_enter(self):
        self.update_dashboard()

    def update_dashboard(self):
        stats = App.get_running_app().system.get_statistics()
        self.total_txns = str(stats['total_transactions'])
        self.flagged_txns = str(stats['flagged_transactions'])
        self.fraud_rate = f"{stats['fraud_detection_rate']:.1f}%"
        self.risk_amount = f"${stats['flagged_amount']:.2f}"

class CreateAccountScreen(Screen):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.name = 'create_account'

class ProcessTransactionScreen(Screen):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.name = 'process_transaction'

class TransactionResultScreen(Screen):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.name = 'transaction_result'

# ============================================================================
# MAIN APP
# ============================================================================

class FraudDetectionApp(App):
    def build(self):
        self.title = '🛡️Fraud Detection System'
        self.system = FraudDetectionSystem()

        # Initialize with sample data
        self.initialize_sample_data()

        # Create screen manager
        sm = ScreenManager()

        # Add screens
        sm.add_widget(self.create_dashboard_screen())
        sm.add_widget(self.create_account_screen())
        sm.add_widget(self.create_transaction_screen())
        sm.add_widget(self.create_result_screen())

        return sm

    def initialize_sample_data(self):
        """Initialize with sample accounts"""
        accounts = [
            Account("ACC001", "John Doe", "checking", 15000.00),
            Account("ACC002", "Jane Smith", "savings", 50000.00),
            Account("ACC003", "Bob Johnson", "credit", 25000.00),
        ]

        for account in accounts:
            self.system.create_account(account)

    def create_dashboard_screen(self):
        """Create main dashboard screen"""
        screen = Screen(name='dashboard')
        layout = BoxLayout(orientation='vertical', padding=20, spacing=15)

        # Header
        header = BoxLayout(size_hint_y=0.15)
        title = Label(
            text='[b] 🛡️ Fraud Detection[/b]',
            markup=True,
            font_size='24sp',
            color=(0.2, 0.2, 0.8, 1)
        )
        header.add_widget(title)
        layout.add_widget(header)

        # Stats Grid
        stats_grid = GridLayout(cols=2, spacing=10, size_hint_y=0.35)

        # Stat cards
        self.total_txns_label = Label(
            text='Total Transactions\n[b]0[/b]',
            markup=True,
            font_size='18sp'
        )
        self.flagged_txns_label = Label(
            text='Flagged\n[b][color=ff0000]0[/color][/b]',
            markup=True,
            font_size='18sp'
        )
        self.fraud_rate_label = Label(
            text='Fraud Rate\n[b]0%[/b]',
            markup=True,
            font_size='18sp'
        )
        self.risk_amount_label = Label(
            text='Amount at Risk\n[b]$0[/b]',
            markup=True,
            font_size='18sp'
        )

        stats_grid.add_widget(self.total_txns_label)
        stats_grid.add_widget(self.flagged_txns_label)
        stats_grid.add_widget(self.fraud_rate_label)
        stats_grid.add_widget(self.risk_amount_label)

        layout.add_widget(stats_grid)

        # Buttons
        buttons_layout = BoxLayout(orientation='vertical', spacing=10, size_hint_y=0.5)

        btn_create_account = Button(
            text='Create Account',
            size_hint_y=None,
            height=60,
            background_color=(0.2, 0.6, 0.2, 1),
            font_size='18sp'
        )
        btn_create_account.bind(on_press=lambda x: self.go_to_screen('create_account'))

        btn_process_txn = Button(
            text='Process Transaction',
            size_hint_y=None,
            height=60,
            background_color=(0.2, 0.4, 0.8, 1),
            font_size='18sp'
        )
        btn_process_txn.bind(on_press=lambda x: self.go_to_screen('process_transaction'))

        btn_refresh = Button(
            text='Refresh Dashboard',
            size_hint_y=None,
            height=60,
            background_color=(0.5, 0.5, 0.5, 1),
            font_size='18sp'
        )
        btn_refresh.bind(on_press=self.update_dashboard)

        buttons_layout.add_widget(btn_create_account)
        buttons_layout.add_widget(btn_process_txn)
        buttons_layout.add_widget(btn_refresh)

        layout.add_widget(buttons_layout)

        screen.add_widget(layout)
        return screen

    def create_account_screen(self):
        """Create account creation screen"""
        screen = Screen(name='create_account')
        layout = BoxLayout(orientation='vertical', padding=20, spacing=10)

        # Header
        header = Label(
            text='[b]Create New Account[/b]',
            markup=True,
            size_hint_y=0.1,
            font_size='22sp'
        )
        layout.add_widget(header)

        # Scroll view for form
        scroll = ScrollView(size_hint_y=0.7)
        form = BoxLayout(orientation='vertical', spacing=15, size_hint_y=None)
        form.bind(minimum_height=form.setter('height'))

        # Account ID
        form.add_widget(Label(text='Account ID:', size_hint_y=None, height=30))
        self.acc_id_input = TextInput(size_hint_y=None, height=40, multiline=False)
        form.add_widget(self.acc_id_input)

        # Customer Name
        form.add_widget(Label(text='Customer Name:', size_hint_y=None, height=30))
        self.acc_name_input = TextInput(size_hint_y=None, height=40, multiline=False)
        form.add_widget(self.acc_name_input)

        # Account Type
        form.add_widget(Label(text='Account Type:', size_hint_y=None, height=30))
        self.acc_type_spinner = Spinner(
            text='checking',
            values=('checking', 'savings', 'credit'),
            size_hint_y=None,
            height=40
        )
        form.add_widget(self.acc_type_spinner)

        # Balance
        form.add_widget(Label(text='Initial Balance:', size_hint_y=None, height=30))
        self.acc_balance_input = TextInput(size_hint_y=None, height=40, multiline=False, input_filter='float')
        form.add_widget(self.acc_balance_input)

        scroll.add_widget(form)
        layout.add_widget(scroll)

        # Buttons
        buttons = BoxLayout(size_hint_y=0.2, spacing=10)

        btn_create = Button(
            text='Create Account',
            background_color=(0.2, 0.6, 0.2, 1)
        )
        btn_create.bind(on_press=self.create_account)

        btn_back = Button(
            text='Back',
            background_color=(0.5, 0.5, 0.5, 1)
        )
        btn_back.bind(on_press=lambda x: self.go_to_screen('dashboard'))

        buttons.add_widget(btn_create)
        buttons.add_widget(btn_back)

        layout.add_widget(buttons)
        screen.add_widget(layout)
        return screen

    def create_transaction_screen(self):
        """Create transaction processing screen"""
        screen = Screen(name='process_transaction')
        layout = BoxLayout(orientation='vertical', padding=20, spacing=10)

        # Header
        header = Label(
            text='[b]Process Transaction[/b]',
            markup=True,
            size_hint_y=0.1,
            font_size='22sp'
        )
        layout.add_widget(header)

        # Scroll view for form
        scroll = ScrollView(size_hint_y=0.7)
        form = BoxLayout(orientation='vertical', spacing=15, size_hint_y=None)
        form.bind(minimum_height=form.setter('height'))

        # Transaction ID
        form.add_widget(Label(text='Transaction ID:', size_hint_y=None, height=30))
        self.txn_id_input = TextInput(size_hint_y=None, height=40, multiline=False)
        form.add_widget(self.txn_id_input)

        # Account ID
        form.add_widget(Label(text='Account ID:', size_hint_y=None, height=30))
        self.txn_acc_input = TextInput(size_hint_y=None, height=40, multiline=False)
        form.add_widget(self.txn_acc_input)

        # Amount
        form.add_widget(Label(text='Amount:', size_hint_y=None, height=30))
        self.txn_amount_input = TextInput(size_hint_y=None, height=40, multiline=False, input_filter='float')
        form.add_widget(self.txn_amount_input)

        # Merchant
        form.add_widget(Label(text='Merchant:', size_hint_y=None, height=30))
        self.txn_merchant_input = TextInput(size_hint_y=None, height=40, multiline=False)
        form.add_widget(self.txn_merchant_input)

        # Location
        form.add_widget(Label(text='Location:', size_hint_y=None, height=30))
        self.txn_location_input = TextInput(size_hint_y=None, height=40, multiline=False)
        form.add_widget(self.txn_location_input)

        # Device ID (optional)
        form.add_widget(Label(text='Device ID (optional):', size_hint_y=None, height=30))
        self.txn_device_input = TextInput(size_hint_y=None, height=40, multiline=False)
        form.add_widget(self.txn_device_input)

        scroll.add_widget(form)
        layout.add_widget(scroll)

        # Buttons
        buttons = BoxLayout(size_hint_y=0.2, spacing=10)

        btn_process = Button(
            text='Process Transaction',
            background_color=(0.2, 0.4, 0.8, 1)
        )
        btn_process.bind(on_press=self.process_transaction)

        btn_back = Button(
            text='Back',
            background_color=(0.5, 0.5, 0.5, 1)
        )
        btn_back.bind(on_press=lambda x: self.go_to_screen('dashboard'))

        buttons.add_widget(btn_process)
        buttons.add_widget(btn_back)

        layout.add_widget(buttons)
        screen.add_widget(layout)
        return screen

    def create_result_screen(self):
        """Create transaction result screen"""
        screen = Screen(name='transaction_result')
        layout = BoxLayout(orientation='vertical', padding=20, spacing=15)

        # Header
        header = Label(
            text='[b]Transaction Result[/b]',
            markup=True,
            size_hint_y=0.1,
            font_size='22sp'
        )
        layout.add_widget(header)

        # Result display
        self.result_label = Label(
            text='',
            markup=True,
            size_hint_y=0.7,
            font_size='16sp'
        )
        layout.add_widget(self.result_label)

        # Back button
        btn_back = Button(
            text='Back to Dashboard',
            size_hint_y=0.2,
            background_color=(0.5, 0.5, 0.5, 1)
        )
        btn_back.bind(on_press=lambda x: self.go_to_screen('dashboard'))
        layout.add_widget(btn_back)

        screen.add_widget(layout)
        return screen

    def go_to_screen(self, screen_name):
        """Navigate to a screen"""
        self.root.current = screen_name
        if screen_name == 'dashboard':
            self.update_dashboard()

    def update_dashboard(self, *args):
        """Update dashboard statistics"""
        stats = self.system.get_statistics()
        self.total_txns_label.text = f'Total Transactions\n[b]{stats["total_transactions"]}[/b]'
        self.flagged_txns_label.text = f'Flagged\n[b][color=ff0000]{stats["flagged_transactions"]}[/color][/b]'
        self.fraud_rate_label.text = f'Fraud Rate\n[b]{stats["fraud_detection_rate"]:.1f}%[/b]'
        self.risk_amount_label.text = f'Amount at Risk\n[b]${stats["flagged_amount"]:.2f}[/b]'

    def create_account(self, instance):
        """Create a new account"""
        try:
            account_id = self.acc_id_input.text
            customer_name = self.acc_name_input.text
            account_type = self.acc_type_spinner.text
            balance = float(self.acc_balance_input.text)

            if not account_id or not customer_name:
                self.show_popup("Error", "Please fill all fields")
                return

            account = Account(account_id, customer_name, account_type, balance)
            self.system.create_account(account)

            # Clear inputs
            self.acc_id_input.text = ''
            self.acc_name_input.text = ''
            self.acc_balance_input.text = ''

            self.show_popup("Success", f"Account {account_id} created successfully!")

        except ValueError:
            self.show_popup("Error", "Please enter valid balance")

    def process_transaction(self, instance):
        """Process a transaction"""
        try:
            txn_id = self.txn_id_input.text
            account_id = self.txn_acc_input.text
            amount = float(self.txn_amount_input.text)
            merchant = self.txn_merchant_input.text
            location = self.txn_location_input.text
            device_id = self.txn_device_input.text or None

            if not all([txn_id, account_id, merchant, location]):
                self.show_popup("Error", "Please fill all required fields")
                return

            transaction = Transaction(
                txn_id, account_id, amount, 'debit',
                merchant, location, device_id=device_id
            )

            result = self.system.process_transaction(transaction)

            if 'error' in result:
                self.show_popup("Error", result['error'])
                return

            # Display result
            det = result['detection_result']
            risk_color = 'ff0000' if det['risk_score'] >= 60 else '00ff00'

            result_text = f"""[b]Transaction: {txn_id}[/b]

Amount: ${amount:.2f}
Merchant: {merchant}
Location: {location}

[b][color={risk_color}]Risk Score: {det['risk_score']:.1f}%[/color][/b]
Fraud Probability: {det['fraud_probability']:.1%}
Status: {result['status'].upper()}

Recommendation:
{det['recommendation']}

"""

            if det['flags']:
                result_text += "\n[b]⚠️ Fraud Flags:[/b]\n"
                for flag in det['flags']:
                    result_text += f"• {flag}\n"

            self.result_label.text = result_text

            # Clear inputs
            self.txn_id_input.text = ''
            self.txn_acc_input.text = ''
            self.txn_amount_input.text = ''
            self.txn_merchant_input.text = ''
            self.txn_location_input.text = ''
            self.txn_device_input.text = ''

            # Go to result screen
            self.go_to_screen('transaction_result')

        except ValueError:
            self.show_popup("Error", "Please enter valid amount")

    def show_popup(self, title, message):
        """Show a popup message"""
        from kivy.uix.popup import Popup
        content = BoxLayout(orientation='vertical', padding=10)
        content.add_widget(Label(text=message))
        btn = Button(text='OK', size_hint_y=0.3)
        content.add_widget(btn)

        popup = Popup(title=title, content=content, size_hint=(0.8, 0.4))
        btn.bind(on_press=popup.dismiss)
        popup.open()

if __name__ == '__main__':
    FraudDetectionApp().run()